### PR TITLE
NIT: updated readme for better readability

### PR DESCRIPTION
**Pull request by anmluo**
Minor changes for readme

### CODE REVIEW

**Review by yolocs — APPROVED** [review]

**Review by sethvargo — APPROVED** [review]

**Comment by sethvargo** [comment]
@anmluo - can you [enable commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) on your account? I'll force this merge, but we require all commits to be signed.

**Comment by anmluo** [comment]
@sethvargo I will make all the commits are signed. Already enable it in my account but probably forget to add -S option during commit.

**Comment by sethvargo** [comment]
Add:

```
[commit]
  gpgsign = true

[tag]
  gpgsign = true
```

to your $HOME/.gitconfig :)

**Comment by anmluo** [comment]
cool, added it, thx for the tip.

**Pull request merged**
